### ISSUE TITLE
Changing the headline text more nicely.

### ISSUE THREAD

**Issue by kishu** [kishu/askers#22]
![image](https://user-images.githubusercontent.com/13197080/45145582-f8919c00-b1fb-11e8-9c96-b12ac9e54efd.png)

@taehee3088

**Comment by taehee3088** [comment]
**Welcome (user name)!**

Experience Askers, a new Q&A Platform to communicate, collaborate, and connect.
ㄴor Introducing --> "both OK"
Gain instant access to top level experts and resources for (company) meetings and events.

-------

How about it?
Let me know if this is less impressive or hard to make sense.
